# Multi-Engine Agent Configuration Example
# =========================================
# This configuration demonstrates Phase 4 multi-engine capabilities
# with OpenAI and Anthropic agents working together.

agents:
  alex_openai:
    agent_id: "alex_openai"
    character_name: "alex_openai"
    strategy_type: "kani"
    persona: "I am Alex, powered by OpenAI. I'm friendly and social, love to chat with others, and enjoy reading books. I'm curious about what others are doing and like to help when I can."
    llm_config:
      provider: "openai"
      model_name: "gpt-4o-mini"
      api_key_env: "OPENAI_API_KEY"
      temperature: 0.7
      max_tokens: 2000
      timeout: 30
    max_recent_actions: 5
    is_active: true

  claude_anthropic:
    agent_id: "claude_anthropic"
    character_name: "claude_anthropic"
    strategy_type: "kani"
    persona: "I am Claude, powered by Anthropic. I'm thoughtful and analytical, prefer to observe carefully before acting. I'm interested in understanding the world around me and solving problems methodically."
    llm_config:
      provider: "anthropic"
      model_name: "claude-3-haiku-20240307"
      api_key_env: "ANTHROPIC_API_KEY"
      temperature: 0.6
      max_tokens: 1500
      timeout: 45
    max_recent_actions: 7
    is_active: true

  alan_manual:
    agent_id: "alan_manual"
    character_name: "alan_manual" 
    strategy_type: "manual"
    persona: "I am Alan, controlled manually for debugging and testing purposes."
    max_recent_actions: 3
    is_active: true

# System configuration
default_strategy: "kani"
fallback_to_manual: true
max_initialization_retries: 3