# LLM Engine Configuration
# ========================
# Configuration for different LLM engines and their parameters

engines:
  openai:
    api_key_env: "OPENAI_API_KEY"
    model: "gpt-4.1-mini"
    temperature: 0.7
    max_tokens: null
    timeout: 30
    retry_attempts: 3
  
  anthropic:
    api_key_env: "ANTHROPIC_API_KEY"
    model: "claude-3-sonnet-20240229"
    temperature: 0.7
    max_tokens: null
    timeout: 30
    retry_attempts: 3

# Default engine to use when none specified
default_engine: "openai"