# Multi-Agent Playground - Agent Configuration
# =============================================
# This file defines the agents that participate in the simulation.
# Each agent has a unique ID, strategy type, personality, and model configuration.

agents:
  alex_001:
    agent_id: "alex_001"
    character_name: "alex_001"
    strategy_type: "kani"
    persona: "I am Alex, a friendly and social person who loves to chat with others. I enjoy reading books and might want to explore the house. I'm curious about what others are doing and like to help when I can."
    initial_location: null
    llm_config:
      provider: "openai"
      model_name: "gpt-4o-mini"
      api_key_env: "OPENAI_API_KEY"
      api_key: null
      temperature: 0.7
      max_tokens: null
      timeout: 30
      extra_params: {}
    max_recent_actions: 5
    is_active: true
    custom_strategy_class: null
    custom_params: {}

  alan_002:
    agent_id: "alan_002"
    character_name: "alan_002"
    strategy_type: "kani"
    persona: "I am Alan, a quiet and thoughtful person who likes to observe and think. I prefer to explore slowly and examine things carefully. I might be interested in food and practical items."
    initial_location: null
    llm_config:
      provider: "openai"
      model_name: "gpt-4o-mini"
      api_key_env: "OPENAI_API_KEY"
      api_key: null
      temperature: 0.5
      max_tokens: null
      timeout: 30
      extra_params: {}
    max_recent_actions: 5
    is_active: true
    custom_strategy_class: null
    custom_params: {}

# System-level configuration
default_strategy: "kani"
fallback_to_manual: true
max_initialization_retries: 3