# Office World Configuration
# ========================
# This YAML configuration defines an office environment with different
# locations, items, and characters to demonstrate the multi-scenario
# capability of Phase 5 world building.

game:
  world_name: "office"
  world_description: "A modern office building with various work spaces"
  max_turns_per_session: 800
  starting_location: "lobby"
  win_conditions: []
  lose_conditions: []

locations:
  lobby:
    name: "Lobby"
    description: "A bright lobby with a reception desk and comfortable seating."
    connections:
      north: "main_office"
      east: "meeting_room"
  
  main_office:
    name: "Main Office"
    description: "An open office space with cubicles and workstations."
    connections:
      south: "lobby"
      east: "meeting_room"
      west: "break_room"
      north: "executive_office"
  
  meeting_room:
    name: "Meeting Room"
    description: "A conference room with a large table and presentation screen."
    connections:
      west: "lobby"
      north: "main_office"
  
  break_room:
    name: "Break Room"
    description: "A small break room with kitchen appliances and tables."
    connections:
      east: "main_office"
      north: "supply_room"
  
  executive_office:
    name: "Executive Office"
    description: "A corner office with large windows and executive furniture."
    connections:
      south: "main_office"
  
  supply_room:
    name: "Supply Room"
    description: "A storage room filled with office supplies and equipment."
    connections:
      south: "break_room"

items:
  # Lobby Items
  - name: "reception_desk"
    display_name: "reception desk"
    description: "A modern reception desk with a computer and phone."
    item_type: "furniture"
    location: "lobby"
    properties:
      material: "wood"
      is_gettable: false
  
  - name: "lobby_chair"
    display_name: "comfortable chair"
    description: "A comfortable leather chair for visitors."
    item_type: "furniture"
    location: "lobby"
    properties:
      material: "leather"
      custom_properties:
        comfort_level: "high"

  # Main Office Items
  - name: "desktop_computer"
    display_name: "desktop computer"
    description: "A powerful desktop computer with dual monitors."
    item_type: "electronic"
    location: "main_office"
    properties:
      is_gettable: false
  
  - name: "office_chair"
    display_name: "office chair"
    description: "An ergonomic office chair with adjustable height."
    item_type: "furniture"
    location: "main_office"
    properties:
      material: "mesh"
      custom_properties:
        adjustable: true
  
  - name: "filing_cabinet"
    display_name: "filing cabinet"
    description: "A metal filing cabinet for document storage."
    item_type: "container"
    location: "main_office"
    properties:
      material: "metal"
      is_openable: true
      is_open: false
    contained_items:
      - name: "important_document"
        display_name: "important document"
        description: "A confidential business document."
        item_type: "utility"
        properties:
          utility_type: "document"
      
      - name: "contract"
        display_name: "contract"
        description: "A signed business contract."
        item_type: "utility"
        properties:
          utility_type: "document"

  # Meeting Room Items  
  - name: "conference_table"
    display_name: "conference table"
    description: "A large oval conference table made of polished wood."
    item_type: "furniture"
    location: "meeting_room"
    properties:
      material: "oak"
      custom_properties:
        shape: "oval"
        seats: "12"
  
  - name: "projector"
    display_name: "projector"
    description: "A ceiling-mounted projector for presentations."
    item_type: "electronic"
    location: "meeting_room"
    properties:
      is_gettable: false
  
  - name: "whiteboard"
    display_name: "whiteboard"
    description: "A large whiteboard with markers for brainstorming."
    item_type: "furniture"
    location: "meeting_room"
    properties:
      material: "plastic"
      is_gettable: false

  # Break Room Items
  - name: "coffee_machine"
    display_name: "coffee machine"
    description: "An automatic coffee machine that makes delicious coffee."
    item_type: "electronic"
    location: "break_room"
    properties:
      is_gettable: false
  
  - name: "microwave"
    display_name: "microwave"
    description: "A microwave oven for heating food."
    item_type: "electronic"
    location: "break_room"
    properties:
      is_gettable: false
  
  - name: "refrigerator"
    display_name: "refrigerator"
    description: "A small office refrigerator for storing food."
    item_type: "container"
    location: "break_room"
    properties:
      is_openable: true
      is_open: false
      temperature: "cold"
    contained_items:
      - name: "sandwich"
        display_name: "sandwich"
        description: "A fresh turkey sandwich."
        item_type: "edible"
        properties:
          is_gettable: true
      
      - name: "yogurt"
        display_name: "yogurt"
        description: "A cup of strawberry yogurt."
        item_type: "edible"
        properties:
          is_gettable: true

  # Executive Office Items
  - name: "executive_desk"
    display_name: "executive desk"
    description: "A large mahogany desk with leather inlay."
    item_type: "furniture"
    location: "executive_office"
    properties:
      material: "mahogany"
      custom_properties:
        style: "executive"
  
  - name: "bookshelf"
    display_name: "bookshelf"
    description: "A tall bookshelf filled with business books."
    item_type: "container"
    location: "executive_office"
    properties:
      material: "wood"
    contained_items:
      - name: "business_book"
        display_name: "business book"
        description: "A book about business strategy."
        item_type: "book"
        properties:
          book_title: "Strategic Management"
          book_author: "Michael Porter"
      
      - name: "leadership_book"
        display_name: "leadership book"
        description: "A book about leadership principles."
        item_type: "book"
        properties:
          book_title: "The 7 Habits of Highly Effective People"
          book_author: "Stephen Covey"

  # Supply Room Items
  - name: "printer"
    display_name: "printer"
    description: "A large office printer and scanner."
    item_type: "electronic"
    location: "supply_room"
    properties:
      is_gettable: false
  
  - name: "supply_cabinet"
    display_name: "supply cabinet"
    description: "A cabinet filled with office supplies."
    item_type: "container"
    location: "supply_room"
    properties:
      is_openable: true
      is_open: false
    contained_items:
      - name: "stapler"
        display_name: "stapler"
        description: "A heavy-duty office stapler."
        item_type: "utility"
        properties:
          utility_type: "office_supply"
      
      - name: "paper_clips"
        display_name: "paper clips"
        description: "A box of metal paper clips."
        item_type: "utility"
        properties:
          utility_type: "office_supply"
      
      - name: "pens"
        display_name: "pens"
        description: "A pack of blue ballpoint pens."
        item_type: "utility"
        properties:
          utility_type: "office_supply"

characters:
  - name: "alex_001"
    display_name: "Alex"
    description: "Alex is a project manager who loves organizing and coordinating team activities."
    initial_location: "main_office"
    persona: "I am Alex, a project manager who loves organizing and coordinating team activities. I enjoy working with technology and helping colleagues be productive. I'm always looking for ways to improve office workflows."
    is_npc: true
    properties: {}
  
  - name: "alan_002"
    display_name: "Alan"
    description: "Alan is a software developer who prefers quiet spaces for coding and thinking."
    initial_location: "executive_office"
    persona: "I am Alan, a software developer who prefers quiet spaces for coding and thinking. I enjoy reading technical books and exploring new technologies. I often need coffee to stay focused and productive."
    is_npc: true
    properties: {}